# Generated by Django 3.1.7 on 2021-03-07 06:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=660)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('body', ckeditor.fields.RichTextField(default=False)),
            ],
        ),
    ]
