# Generated by Django 3.1.7 on 2021-03-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminarea', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
